apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
spec:
  selector:
    app: task-manager
  type: NodePort    
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
      nodePort: 30008